version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '1000' # Cambia si tu UID es diferente
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - pgsql
    command: >
        sh -c "
            if [ ! -d node_modules ]; then
            npm install;
            fi &&
            npm run dev &
            php artisan serve --host=0.0.0.0 --port=80"

  pgsql:
    image: 'postgres:17'
    container_name: pgsql
    ports:
      - '${FORWARD_DB_PORT:-5433}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

networks:
  laravel:
    driver: bridge

volumes:
  pgsql_data:
    driver: local
